### ISSUE TITLE
arXiv as data source

### ISSUE THREAD

**Issue by Ohjeah** [texworld/betterbib#102]
- If a bibtex entry has a `arxiv.org` url, betterbib should fill in author, title, year, archivePrefix, eprint and primaryClass.
-  If it does have a valid journal field, pubstatus should be set to submitted; else the type should be changed from article to misc.

See also https://arxiv.org/help/faq/references

**Comment by leofang** [comment]
Another ref: https://tex.stackexchange.com/a/3848/29961 @nschloe If this suggestion is acceptable to you, I can create a PR. Thanks.

**Comment by avivace** [comment]
Any update on this?

**Comment by zerothi** [comment]
This would be amazing!

**Comment by nschloe** [comment]
Five years old, and finally fixed! :) betterbib 7 can also fetch data from arXiv now.
