### ISSUE TITLE
check out https://tex.stackexchange.com/questions/6848/automatically-dereference-doi-to-bib

### ISSUE THREAD

**Issue by nschloe** [texworld/betterbib#11]
- [ ] https://tex.stackexchange.com/questions/6848/automatically-dereference-doi-to-bib
- [ ] http://crosscite.org/cn/

**Comment by nschloe** [comment]
http://crosscite.org/cn/

**Comment by thorade** [comment]
Just found this:
https://doi2bib.org/about
and added it to the SO question linked above.
They mention an open interface, could that be used here as well?

**Comment by nschloe** [comment]
@thorade It's a DOI-to-BibTeX converter -- betterbib goes beyond that. (It's got a doi2bibtex as a gimmick though.)

**Comment by nschloe** [comment]
betterbib has has `doi-to-bibtex` for long now.
