### ISSUE TITLE
Support custom name and list seps

### ISSUE THREAD

**Issue by alexreg** [texworld/betterbib#177]
It would be nice to support custom separators in name lists (see `--listsep` and `--namesep` options of `biber --tool`).

**Comment by nschloe** [comment]
I understand `namesep`, but where is `listsep` used?

**Comment by alexreg** [comment]
I'm not sure exactly, to be honest! I just know biber provides an option for it.

**Comment by alexreg** [comment]
The [official manual](http://mirror.ox.ac.uk/sites/ctan.org/biblio/biber/documentation/biber.pdf) (§3.7) isn't too clear on this, but [this TeX.SE answer](https://tex.stackexchange.com/questions/526701/how-to-escape-and-as-list-delimiter-in-bibtex-biblatex) may clarify the situation. It seems `--listsep` applies to fields like `organization`, `publisher`, `institution`.
