### ISSUE TITLE
Character escaping

### ISSUE THREAD

**Issue by haji-ali** [texworld/betterbib#243]
Thank you again for implementing the escaping of characters and using LaTeX commands instead of unicode. I have a large bibliography which betterbib processes almost perfectly. 

However, I noticed the following problems:
- For fields or entries that are not in CrossRef, betterbib escapes characters when it shouldn't. Perhaps escaping characters should _not_ be done to fields that are already in the bib file, but for those that are obtained from external sources.

- Characters (like `_`) in url and doi should _not_ be escaped (even if the entry is obtained from external sources).

```
@inproceedings{randompaper,
 author = {J\"oe D\'oe},
 editor = {de Groen, P. and Beauwens, R.},
 title = {An \^intesting title},
 booktitle = {{My book}},
 url={https://doi.org/10.1007/978-3-319-04537-5_3},
 doi={10.1007/978-3-319-04537-5_3},
}
```
which outputs
```
@inproceedings{randompaper,
 author = {D{\textbackslash}'oe, J{\textbackslash}''oe},
 editor = {de Groen, P. and Beauwens, R.},
 title = {An \^intesting title},
 booktitle = {\{My book\}},
 url = {https://doi.org/10.1007/978-3-319-04537-5\_3},
 doi = {10.1007/978-3-319-04537-5\_3},
}
```

Running `betterbib` again leads to more unnecessary escaping.

```
@inproceedings{randompaper,
 author = {D\{{\textbackslash}textbackslash\}'oe, J\{{\textbackslash}textbackslash\}''oe},
 editor = {de Groen, P. and Beauwens, R.},
 title = {An \^intesting--title},
 booktitle = {{\textbackslash}\{My book{\textbackslash}\}},
 url = {https://doi.org/10.1007/978-3-319-04537-5{\textbackslash}\_3},
 doi = {10.1007/978-3-319-04537-5{\textbackslash}\_3},
}
```

**Comment by nschloe** [comment]
Unfortunately, I have no time for this anymore right now.

**Comment by nschloe** [comment]
This is now fixed.
