### ISSUE TITLE
Run update as pre-commit hook: libenchant

### ISSUE THREAD

**Issue by akhmerov** [texworld/betterbib#244]
I'm trying to configure `betterbib update` to work as a pre-commit hook, but right now it [fails](https://results.pre-commit.ci/run/github/440568287/1642160466.nTmIyCCLT1GwWrIqslhzSQ) because of lacking `libenchant`. Is there no workaround?

**Comment by nschloe** [comment]
Install libenchant?

**Comment by akhmerov** [comment]
I'm not sure how to achieve this within pre-commit paradigm. I understand that it works locally due to relying on a globally installed library, but I don't think this would work e.g. in pre-commit CI.

**Comment by akhmerov** [comment]
There the two pathways are either specifying dependencies using conda or pip, and conda-forge version of libenchant seems to not work with pyenchant: I see `OSError: /home/anton/miniconda3/envs/py39/lib/enchant-2: cannot read file data: Is a directory`

**Comment by nschloe** [comment]
Perhaps pyenchant can be replaced with something more portable, e.g., [pyspellchecker](https://github.com/barrust/pyspellchecker).

**Comment by nschloe** [comment]
This is blocked by https://github.com/barrust/pyspellchecker/issues/122.

**Comment by akhmerov** [comment]
Wow, excellent, thank you very much!
