### ISSUE TITLE
Feature request: Protect entries

### ISSUE THREAD

**Issue by jtplaarj** [texworld/betterbib#246]
I would find it very interesting if though the use of some bibtex entry I could protect the entry from being updated by betterbib. For example

```tex
@article{test,
betterbib = {Do not touch},
title = {Some very nice article},
}
```
The reason is that sometimes there are very similar articles by the same authors and betterbib updates it to the one I do not want :cry:.

**Comment by nschloe** [comment]
This is now possible: Just add
```
protect = {true}
```
to the BibTeX entry and betterbib won't touch it.
