### ISSUE TITLE
Search for retractions

### ISSUE THREAD

**Issue by clbarnes** [texworld/betterbib#249]
The largest retraction database (retractionwatch) doesn't have an API, but [openretractions does](https://github.com/open-retractions/open-retractions#api). A tool to go through your .bib and raise retractions and other updates would be valuable, and should only require the DOI.

**Comment by nschloe** [comment]
This is now implemented. :tada:

**Comment by clbarnes** [comment]
I got most of the way through an implementation too, but stalled when it turned out openretractions' database is very patchy. I picked a few DOIs from [retractionwatch's top 10 most cited](https://retractionwatch.com/the-retraction-watch-leaderboard/top-10-most-highly-cited-retracted-papers/) and openretractions had none of them. It may be worth mentioning which database your implementation uses in the docs so that people can be aware of any caveats associated with it.

**Comment by nschloe** [comment]
Add this to the readme and help. Let me know if you find any better site for this.

**Comment by clbarnes** [comment]
I did contact retractionwatch about making their data available over an API; they said it's something they'd like to do and existed somewhere on the backlog but wasn't a priority and they had limited dev time.

**Comment by nschloe** [comment]
Ha, I feel that. :smile_cat:
