### ISSUE TITLE
Allow project-local configuration, optionally ignoring global config

### ISSUE THREAD

**Issue by clbarnes** [texworld/betterbib#250]
When collaborating on a document or using CI, it's useful for formatters/ fixers to be able to use the same config and no other to get reproducible results across environments. For example, editorconfig allows you to set a local configuration, which has a `root` field to prevent it looking for config elsewhere.

If the config grows in complexity, merging configurations might get tricky.

**Comment by nschloe** [comment]
Basically a dup of https://github.com/texworld/betterbib/issues/207, closing for the same reason.
