### ISSUE TITLE
Openretraction name unresolved & Betterbib not working

### ISSUE THREAD

**Issue by dbcliu** [texworld/betterbib#254]
Today when I ran Betterbib, it stopped working with error:

requests.exceptions.ConnectionError: HTTPConnectionPool(host='openretractions.com', port=80): Max retries exceeded with url: /api/doi/10.1103/physrevlett.58.2059/data.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60cc14f730>: Failed to establish a new connection: [Errno -2] Name or service not known'))

And I find that the name openretractions.com is not resolved anymore. It may cause Betterbib to stop working.

**Comment by dbcliu** [comment]
Adding "192.30.252.153 openretractions.com" to the host file can temporarily solve this problem.

**Comment by nschloe** [comment]
Seems fixed upstream.

**Comment by jeffrey-hokanson** [comment]
I am encountering this bug as of 21 Feb 2023. Openretractions seems to be down. I would prefer the code to fail gracefully if it cannot access this resource. (I would be happy to commit a fix, but there seems to be no code in this repo.)

**Comment by nschloe** [comment]
This has been fixed by disabling openretractions by default in the latest release. Note that 5.0 is also the first commerical release of betterbib.
