### ISSUE TITLE
license 

### ISSUE THREAD

**Issue by emilBeBri** [texworld/betterbib#258]
so suddenly you need a license. But no where does it state HOW to get a license. pretty stupid.

**Comment by nschloe** [comment]
Hi Emil,

Thanks for opening an issue! We've postponed the release a bit, so a simple upgrade should fix your issues. When a proper release is ready, all information will be made available.

Let us know if you have any further issues!

Cheers,
Nico

**Comment by vitorsr** [comment]
> so suddenly you need a license. But no where does it state HOW to get a license. pretty stupid.

@emilBeBri I understand your frustration as I used this tool quite heavily to maintain my personal reference library and now it appears to be closed-source. I used to be able to probe into the source to quash problems about certain implementation aspects and make my own quick patches but now it is only published as obfuscated Python sources on PyPI.

The original project used to be GNU's GPL-3.0-or-later. You read that right: GNU GPL. 3 nonetheless. Or later.

However, the author has deleted all previous versions on PyPI, moved the repository to this organization, and rewritten the Git history.

I am not privy of anyone's personal intentions but this indeed comes off as user-hostile.

**Comment by vitorsr** [comment]
That said, here is the Python source package for an earlier distribution.

[betterbib-4.0.2.tar.gz](https://github.com/texworld/betterbib/files/10431121/betterbib-4.0.2.tar.gz)

```
MD5	02f778e319db5692231166aef81322bf
SHA-1	9fbbfdfa1f192eb0ccc7ea54ac18017eb2cc8ce0
SHA-256	70696682d1b7067380e069ff4d3f1a680149457db257ac41b1ea3892959ef8db
```

https://www.virustotal.com/gui/file/70696682d1b7067380e069ff4d3f1a680149457db257ac41b1ea3892959ef8db/details

**Comment by vitorsr** [comment]
Here are a few others.

https://files.pythonhosted.org/packages/d7/60/13e0b6c291cea8c949d364bad5cdd64c597a8cf865e9fd9fb0f494adefed/betterbib-4.1.1-py3-none-any.whl

```
MD5	d2b880630a92fc15b774427f5b8ae783
SHA-1	ee14ddfd069ff87301d5abb2c89c47af9018e95d
SHA-256	fc820acc60a56f5f88c96f62cfbf91cba1c0a21d3db075b50b1ff76ba3d92e33
```

https://www.virustotal.com/gui/file/fc820acc60a56f5f88c96f62cfbf91cba1c0a21d3db075b50b1ff76ba3d92e33/details

---

https://files.pythonhosted.org/packages/a3/01/1be9a70c4e358fbd2d55f3706067cef6a897fc2843e28065e97f68184e88/betterbib-4.0.7-py3-none-any.whl

```
MD5	0d31ddaa05f2fc80ce3cda0d2c305a12
SHA-1	5d431073ed3758ef2a772cdae8e7b4380f7b43c8
SHA-256	e91036a87fc7ec68bbaf3a3dea95a70fb8b9136fe753ffb1002506d1ae5aaf36
```

https://www.virustotal.com/gui/file/e91036a87fc7ec68bbaf3a3dea95a70fb8b9136fe753ffb1002506d1ae5aaf36/details

---

https://files.pythonhosted.org/packages/a9/29/1d2e7716f093d8a207721b98f1f55985d96d91e58b4dd8d48fa0f8b0af96/betterbib-4.0.6-py3-none-any.whl

```
MD5	da7896962f00d6f03526296f5115894f
SHA-1	141d9c5027afcd780cf510246845b05e4fc112dc
SHA-256	411ec6444417910674ba1a981343a188339f9fe59b80b0a69fbd43e3c61ddbb2
```

https://www.virustotal.com/gui/file/411ec6444417910674ba1a981343a188339f9fe59b80b0a69fbd43e3c61ddbb2/details

---

https://files.pythonhosted.org/packages/97/76/9626f963c3cf602089fa8fe291e30a297ea838f0a3c1bf87601dbcdb84d9/betterbib-4.0.4-py3-none-any.whl

```
MD5	63085541c162540431ba2dd3a63166a2
SHA-1	0650fdabf0a7f57b2dadb53611539ea4b80d6455
SHA-256	95f332ed565c0443b73d472737db61838ec131f7701e501bd49d0bc8ceb4b6b3
```

https://www.virustotal.com/gui/file/95f332ed565c0443b73d472737db61838ec131f7701e501bd49d0bc8ceb4b6b3/details

**Comment by emilBeBri** [comment]
I got your comment Victor thank you.  Leaving this project behind
