### ISSUE TITLE
Updating a bibtex with a doi may result in totally different article

### ISSUE THREAD

**Issue by zerothi** [texworld/betterbib#260]
For instance this DOI: `10.11581/DTU:00000025` will have a hard time following information.

I created a bib:
```
@phdthesis{Papior,
    doi = {10.11581/DTU:00000025},
}
```

Got:
```
<string>:165: UserWarning: 'entry' Entry('phdthesis',
  fields=[
    ('doi', '10.11581/DTU:00000025')],
  persons=OrderedCaseInsensitiveDict([])) has no title
```

So clearly the backend cannot find any result. (checking with `doi2bib.org` it successfully finds it.

If i then put in the doi2bib info (which is correct):
```
@article{https://doi.org/10.11581/dtu:00000025,
  doi = {10.11581/DTU:00000025},
  url = {http://orbit.dtu.dk/en/publications/computational-tools-and-studies-of-graphene-nanostructures(46f34e1c-5f0c-46cb-be32-fff5f37881aa).html},
  author = {R\"{u}bner Papior,  Nick},
  title = {Computational Tools and Studies of Graphene Nanostructures},
  publisher = {Department of Micro- and Nanotechnology,  Technical University of Denmark,  2800,  Kgs. Lyngby,  Denmark},
  year = {2016}
}
```
I once got it to change it to a completely different article. Now I have tried a couple of times but cannot reproduce.

I would suspect that there is a check if the `doi` is already present, that this should not be changed? Is there such a check?

**Comment by nschloe** [comment]
Thanks for the feedback! The DOI (if present) is now always honored. This makes typos in DOIs more catastrophic, but we'll have to rely on _something_ after all.

**Comment by zerothi** [comment]
Hurray! Thanks
