### ISSUE TITLE
doi-to-bib should be able to accept a list and/or file

### ISSUE THREAD

**Issue by zerothi** [texworld/betterbib#261]
Instead of doing the doi-to-bib for individual doi's, it might be useful to do:

```
betterbib doi-to-bib <list-file>
```
or even just a variable number of doi's on the cmd line.

In this line of thought it might be valuable to overwrite keys in a file, such as:

```
10.1234/123 @key=MyKey
```
or similar.

I would be happy to help out here, let me know.

**Comment by nschloe** [comment]
Fixed now. Thanks for the suggestion!

**Comment by zerothi** [comment]
Super, great!
