### ISSUE TITLE
openretractions.com failed

### ISSUE THREAD

**Issue by yakeworld** [texworld/betterbib#264]
requests.exceptions.ConnectionError: HTTPConnectionPool(host='openretractions.com', port=80): Max retries exceeded with url: /api/doi/10.1177/003591575204500604/data.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feab82ca150>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by nschloe** [comment]
Dup of #262.
