### ISSUE TITLE
Getting error from RequestsJSONDecodeError

### ISSUE THREAD

**Issue by hooli67** [texworld/betterbib#271]
When update the bib file, get the following error:

in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by nschloe** [comment]
That's weird. Can you give me a (small) bibtex file that reproduces the issue? Updating to betterbib 6.* might also help.
