### ISSUE TITLE
biblatex flavor of betterbib

### ISSUE THREAD

**Issue by dbitouze** [texworld/betterbib#57]
It would be nice to have a `biblatex` flavor of `betterbib`.

**Comment by nschloe** [comment]
What exactly do you mean by that?

**Comment by dbitouze** [comment]
For instance, the input BibTex

```
@article {krylov,
  author = {Liesen and Gaul and Nabben},
  title = {Framework Deflation Krylov Augmented}
}
```

would be converted into the following `biblatex` code:

```
@Article{krylov,
  author       = {Gaul, André and Gutknecht, Martin H. and Liesen, Jörg and Nabben, Reinhard},
  title        = {A Framework for Deflated and Augmented {Krylov} Subspace Methods},
  journaltitle = {SIAM J. Matrix Anal. \& Appl.},
  date         = {2013-01},
  volume       = {34},
  number       = {2},
  pages        = {495-518},
  doi          = {10.1137/110820713},
  publisher    = {Society for Industrial \& Applied Mathematics (SIAM)},
  source       = {Crossref},
}
```

There are not very many differences between the two syntax but some of them could be noted, e.g. the `date` field at ISO format instead of `year` (number) + `month` (string, subject to errors).

See e.g. https://tex.stackexchange.com/a/2974/18401 for some of the advantages of `biblatex` over the old `bibtex`.

**Comment by nschloe** [comment]
Thanks for the info! I never knew that biblatex/biber actually allow for a different syntax here and there. As a bookmark for myself, let me mention [this overview](https://tex.stackexchange.com/a/37133/13262) of differences and [the biblatex manual](http://mirrors.ibiblio.org/CTAN/macros/latex/contrib/biblatex/doc/biblatex.pdf).

The question whether or not this can be implemented quickly probably depends on how well pybtex supports the biblatex syntax. I'll check that out later.

**Comment by dbitouze** [comment]
>Thanks for the info

You're welcome!

>The question whether or not this can be implemented quickly [...]

There is no pressing urgency  :)

**Comment by LukasCBossert** [comment]
Any news on that issue?

**Comment by nschloe** [comment]
Depends on https://bitbucket.org/pybtex-devs/pybtex/issues/131/biblatex-compatibility.

**Comment by nschloe** [comment]
This is now fixed in betterbib 7! Full unicode support, together with the other specialities of biblatex is here.
